### PR TITLE
Migrate to PKGBUILD based postinstall bootstrapping

### PR DESCRIPTION
**Pull request by port19x**
The main difference with this approach is scope:
The PKGBUILD is responsible for installing programms and symlinking configs only.

Configuration that is missing here, but was in dot-install:
- disabling wifi powersave
- installing yay
- cleaning portals
- enabling bluetooth
- enabling reflector service
- gtk settings (adwaita dark & papirus dark)

Some, but not all of this can be reintroduced within the PKGBUILD

### CODE REVIEW

**Comment by port19x** [comment]
If you adopt this pattern it may be a good idea to rebase away the commits of SolDoesTech

**Comment by woolw** [comment]
some of the packages like brave-bin are also aur iirc

**Comment by port19x** [comment]
yes, I didn't spot that because I also have it installed

**Comment by port19x** [comment]
@woolw

**Comment by woolw** [comment]
ah yes.... this still exists xD

**Comment by port19x** [comment]
- [ ] Add auxiliary script to install yay + aur dependencies

**Comment by port19x** [comment]
I guess let's just abandon this PR

**Pull request closed without merging**
